name: teriiehina's blog
description: "Programmer"
meta_description: "Programming"

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://teriiehina.github.io/'

# Details for the RSS feed generator
url:            'http://teriiehina.github.io/'
author:         'Peter MEUEL'
authorTwitter:  'teriiehina'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
